### ISSUE TITLE
[GCP Fileshare Support Request] Need to standarize AK/SK lengths 

### ISSUE THREAD

**Issue by himanshuvar** [sodafoundation/dashboard#408]
**Issue/Feature Description:** We need to standardize AK/SK lengths for utilizing them for the framework for supporting Encryption/Decryption. Suggested size for Ak is 16 & for SK is 32

**Why this issue to fixed / feature is needed(give scenarios or use cases):** To support Encryption/Decryption for multi-cloud GCP Fileshare support

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by anvithks** [comment]
@himanshuvar Have you verified if making this change will affect existing functionality and operation?
@kumarashit At the moment the AK/SK generation is being initiated from the frontend and the generation methods are in the frontend code. 
This length is set as 20 for AK and 40 for SK.
Since this AK/SK i used for all the multicloud features we must test it before pushing the change to master.

**Comment by himanshuvar** [comment]
@anvithks I have tested from backend. Everything works fine. Please check and test from frontend.

**Comment by himanshuvar** [comment]
@anvithks @kumarashit  FYI, AK/SK can be generated at backend. I have verified.

**Comment by anvithks** [comment]
This is good news @himanshuvar 
If AK/SK can be generated in the backend then it should be part of the API . That would make it more secure and also available to all clients.
