### ISSUE TITLE
Backend Type, Region, End point etc  are not listed to register a storage backend

### ISSUE THREAD

**Issue by reshmi-tr** [sodafoundation/dashboard#446]
Steps Used:
1. Click on the "+" symbol in the center of the screen.
2. Enter the name of Backend. (Min 1 char, Max 31 char, no special char except underscore, hyphen)
3. Select the type: AWS, Huawei OBS, Azure Blob Storage, Ceph S3, GCP Storage, FusionStorage Object, IBM COS
=> Type is not Listing
4. Enter the Region, Endpoint, Bucket Name, Access Key and Secret Key.
=> All the fields mentioned in step 4 is not displayed

**Comment by anvithks** [comment]
@reshmi-tr Could you please share some more information.
- SODA Installation version
- SODA Dashboard version
- OS

 This usually happens if the installation was not completed cleanly or the API is not responding.

Could you post the screenshot from the network tab in the developer console for the types API.

Please do check the if all the docker images are running.

you can check this by using `docker ps -a ` on the host where you installed SODA.

**Comment by reshmi-tr** [comment]
Tested on  below remote machine
remote desktop  :  121.244.95.60:12493
password : Ht!pl@2020
dashboard user/passwd : admin / opensds@123

**Comment by anvithks** [comment]
@reshmi-tr deleted your previous comment as it contained some credentials

**Comment by anvithks** [comment]
After discussion with @reshmi-tr the issue was with the installation not being clean. Due to this the backend and other multicloud docker containers were not up and running. The APIs were failing and the types were not returned.

Not an issue on dashboard.
